baseURL: "https://shivaninayakam.netlify.app/"
languageCode: en-us
title: Shivani Nayakam
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
   
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: education
      name: Education
      url: /education
      weight: 40
    - identifier: experience
      name: Experience
      url: /experience
      weight: 20
    - identifier: skills
      name: Skills
      url: /skills/technicalskills/
      weight: 50
   
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: false
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Shivani Nayakam"
    subtitle: With three years of work experience at Deloitte USI, I'm currently enhancing my expertise through a Master's in Computer Science at the University of Florida. I am good at multiple programming languages, has received accolades for my performance improvements and user experience enhancements, and is driven to innovate in software development.My career goal is to leverage my extensive knowledge in computer science and experience in software engineering to innovate and enhance technology applications, contribute to cutting-edge development projects, and drive significant advancements in software solutions and user experience.
    imageUrl: "home/shivani_nayakam.jpg"
    imageWidth: 300
    imageHeight: 250
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1Koyo-RnKFm5ioP-jnb1oOZLrSm_lj0o4/view"

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:nayakamshivani@gmail.com"
    - name: "linkedin"
      url: "https://linkedin.com/in/shivani-nayakam"
    - name: "github"
      url: "https://github.com/nayakamshivani"
 

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
